module TgBotAPI.Types.InlineQueryResultGif where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultGif
instance Show InlineQueryResultGif
instance Eq InlineQueryResultGif
instance FromJSON InlineQueryResultGif
instance ToJSON InlineQueryResultGif
data InlineQueryResultGifThumbMimeType
instance Show InlineQueryResultGifThumbMimeType
instance Eq InlineQueryResultGifThumbMimeType
instance FromJSON InlineQueryResultGifThumbMimeType
instance ToJSON InlineQueryResultGifThumbMimeType
