module TgBotAPI.Types.InlineQueryResultCachedDocument where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultCachedDocument
instance Show InlineQueryResultCachedDocument
instance Eq InlineQueryResultCachedDocument
instance FromJSON InlineQueryResultCachedDocument
instance ToJSON InlineQueryResultCachedDocument
