module TgBotAPI.Types.InlineQueryResultContact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultContact
instance Show InlineQueryResultContact
instance Eq InlineQueryResultContact
instance FromJSON InlineQueryResultContact
instance ToJSON InlineQueryResultContact
