module TgBotAPI.Types.InlineQueryResultCachedVideo where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultCachedVideo
instance Show InlineQueryResultCachedVideo
instance Eq InlineQueryResultCachedVideo
instance FromJSON InlineQueryResultCachedVideo
instance ToJSON InlineQueryResultCachedVideo
