module TgBotAPI.Types.InlineQueryResultCachedSticker where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultCachedSticker
instance Show InlineQueryResultCachedSticker
instance Eq InlineQueryResultCachedSticker
instance FromJSON InlineQueryResultCachedSticker
instance ToJSON InlineQueryResultCachedSticker
