module TgBotAPI.Types.InlineQueryResultCachedMpeg4Gif where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultCachedMpeg4Gif
instance Show InlineQueryResultCachedMpeg4Gif
instance Eq InlineQueryResultCachedMpeg4Gif
instance FromJSON InlineQueryResultCachedMpeg4Gif
instance ToJSON InlineQueryResultCachedMpeg4Gif
