module TgBotAPI.Types.InlineQueryResultMpeg4Gif where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultMpeg4Gif
instance Show InlineQueryResultMpeg4Gif
instance Eq InlineQueryResultMpeg4Gif
instance FromJSON InlineQueryResultMpeg4Gif
instance ToJSON InlineQueryResultMpeg4Gif
data InlineQueryResultMpeg4GifThumbMimeType
instance Show InlineQueryResultMpeg4GifThumbMimeType
instance Eq InlineQueryResultMpeg4GifThumbMimeType
instance FromJSON InlineQueryResultMpeg4GifThumbMimeType
instance ToJSON InlineQueryResultMpeg4GifThumbMimeType
