module TgBotAPI.Types.InlineQueryResultMpeg4Gif where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultMpeg4Gif
instance Show InlineQueryResultMpeg4Gif
instance Eq InlineQueryResultMpeg4Gif
instance FromJSON InlineQueryResultMpeg4Gif
instance ToJSON InlineQueryResultMpeg4Gif
data ThumbMimeType
instance Show ThumbMimeType
instance Eq ThumbMimeType
instance FromJSON ThumbMimeType
instance ToJSON ThumbMimeType
