module TgBotAPI.Types.InlineQueryResultLocation where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InlineQueryResultLocation
instance Show InlineQueryResultLocation
instance Eq InlineQueryResultLocation
instance FromJSON InlineQueryResultLocation
instance ToJSON InlineQueryResultLocation
