module TgBotAPI.Types.InputVenueMessageContent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InputVenueMessageContent
instance Show InputVenueMessageContent
instance Eq InputVenueMessageContent
instance FromJSON InputVenueMessageContent
instance ToJSON InputVenueMessageContent
