module TgBotAPI.Types.MessageAutoDeleteTimerChanged where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data MessageAutoDeleteTimerChanged
instance Show MessageAutoDeleteTimerChanged
instance Eq MessageAutoDeleteTimerChanged
instance FromJSON MessageAutoDeleteTimerChanged
instance ToJSON MessageAutoDeleteTimerChanged
