module TgBotAPI.Types.PassportElementErrorReverseSide where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PassportElementErrorReverseSide
instance Show PassportElementErrorReverseSide
instance Eq PassportElementErrorReverseSide
instance FromJSON PassportElementErrorReverseSide
instance ToJSON PassportElementErrorReverseSide
data Type
instance Show Type
instance Eq Type
instance FromJSON Type
instance ToJSON Type
