-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE DuplicateRecordFields #-}

-- | Contains the types generated from the schema PassportFile
module TgBotAPI.Types.PassportFile where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified TgBotAPI.Common
import TgBotAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.PassportFile@ in the specification.
-- 
-- This object represents a file uploaded to Telegram Passport. Currently all Telegram Passport files are in JPEG format when decrypted and don\'t exceed 10MB.
data PassportFile = PassportFile {
  -- | file_date: Unix time when the file was uploaded
  fileDate :: GHC.Int.Int64
  -- | file_id: Identifier for this file, which can be used to download or reuse the file
  , fileId :: Data.Text.Internal.Text
  -- | file_size: File size
  , fileSize :: GHC.Int.Int64
  -- | file_unique_id: Unique identifier for this file, which is supposed to be the same over time and for different bots. Can\'t be used to download or reuse the file.
  , fileUniqueId :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PassportFile
    where toJSON obj = Data.Aeson.Types.Internal.object ("file_date" Data.Aeson.Types.ToJSON..= fileDate obj : "file_id" Data.Aeson.Types.ToJSON..= fileId obj : "file_size" Data.Aeson.Types.ToJSON..= fileSize obj : "file_unique_id" Data.Aeson.Types.ToJSON..= fileUniqueId obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("file_date" Data.Aeson.Types.ToJSON..= fileDate obj) GHC.Base.<> (("file_id" Data.Aeson.Types.ToJSON..= fileId obj) GHC.Base.<> (("file_size" Data.Aeson.Types.ToJSON..= fileSize obj) GHC.Base.<> ("file_unique_id" Data.Aeson.Types.ToJSON..= fileUniqueId obj))))
instance Data.Aeson.Types.FromJSON.FromJSON PassportFile
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PassportFile" (\obj -> (((GHC.Base.pure PassportFile GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_date")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_size")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "file_unique_id"))
-- | Create a new 'PassportFile' with all required fields.
mkPassportFile :: GHC.Int.Int64 -- ^ 'fileDate'
  -> Data.Text.Internal.Text -- ^ 'fileId'
  -> GHC.Int.Int64 -- ^ 'fileSize'
  -> Data.Text.Internal.Text -- ^ 'fileUniqueId'
  -> PassportFile
mkPassportFile fileDate fileId fileSize fileUniqueId = PassportFile{fileDate = fileDate,
                                                                    fileId = fileId,
                                                                    fileSize = fileSize,
                                                                    fileUniqueId = fileUniqueId}
