module TgBotAPI.Types.PassportElementError where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PassportElementError
instance Show PassportElementError
instance Eq PassportElementError
instance FromJSON PassportElementError
instance ToJSON PassportElementError
data PassportElementErrorType
instance Show PassportElementErrorType
instance Eq PassportElementErrorType
instance FromJSON PassportElementErrorType
instance ToJSON PassportElementErrorType
