-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE DuplicateRecordFields #-}

-- | Contains the types generated from the schema PassportElementErrorUnspecified
module TgBotAPI.Types.PassportElementErrorUnspecified where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified TgBotAPI.Common
import TgBotAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.PassportElementErrorUnspecified@ in the specification.
-- 
-- Represents an issue in an unspecified place. The error is considered resolved when new data is added.
data PassportElementErrorUnspecified = PassportElementErrorUnspecified {
  -- | element_hash: Base64-encoded element hash
  elementHash :: Data.Text.Internal.Text
  -- | message: Error message
  , message :: Data.Text.Internal.Text
  -- | source: Error source, must be *unspecified*
  , source :: Data.Text.Internal.Text
  -- | type: Type of element of the user\'s Telegram Passport which has the issue
  , type' :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PassportElementErrorUnspecified
    where toJSON obj = Data.Aeson.Types.Internal.object ("element_hash" Data.Aeson.Types.ToJSON..= elementHash obj : "message" Data.Aeson.Types.ToJSON..= message obj : "source" Data.Aeson.Types.ToJSON..= source obj : "type" Data.Aeson.Types.ToJSON..= type' obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("element_hash" Data.Aeson.Types.ToJSON..= elementHash obj) GHC.Base.<> (("message" Data.Aeson.Types.ToJSON..= message obj) GHC.Base.<> (("source" Data.Aeson.Types.ToJSON..= source obj) GHC.Base.<> ("type" Data.Aeson.Types.ToJSON..= type' obj))))
instance Data.Aeson.Types.FromJSON.FromJSON PassportElementErrorUnspecified
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PassportElementErrorUnspecified" (\obj -> (((GHC.Base.pure PassportElementErrorUnspecified GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "element_hash")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "message")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "source")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))
-- | Create a new 'PassportElementErrorUnspecified' with all required fields.
mkPassportElementErrorUnspecified :: Data.Text.Internal.Text -- ^ 'elementHash'
  -> Data.Text.Internal.Text -- ^ 'message'
  -> Data.Text.Internal.Text -- ^ 'source'
  -> Data.Text.Internal.Text -- ^ 'type''
  -> PassportElementErrorUnspecified
mkPassportElementErrorUnspecified elementHash message source type' = PassportElementErrorUnspecified{elementHash = elementHash,
                                                                                                     message = message,
                                                                                                     source = source,
                                                                                                     type' = type'}
