-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE DuplicateRecordFields #-}

-- | Contains the types generated from the schema ShippingQuery
module TgBotAPI.Types.ShippingQuery where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified TgBotAPI.Common
import TgBotAPI.TypeAlias
import  {-# SOURCE #-}  TgBotAPI.Types.ShippingAddress (ShippingAddress)
import  {-# SOURCE #-}  TgBotAPI.Types.User (User)

-- | Defines the object schema located at @components.schemas.ShippingQuery@ in the specification.
-- 
-- This object contains information about an incoming shipping query.
data ShippingQuery = ShippingQuery {
  -- | from: This object represents a Telegram user or bot.
  from :: User
  -- | id: Unique query identifier
  , id :: Data.Text.Internal.Text
  -- | invoice_payload: Bot specified invoice payload
  , invoicePayload :: Data.Text.Internal.Text
  -- | shipping_address: This object represents a shipping address.
  , shippingAddress :: ShippingAddress
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON ShippingQuery
    where toJSON obj = Data.Aeson.Types.Internal.object ("from" Data.Aeson.Types.ToJSON..= from obj : "id" Data.Aeson.Types.ToJSON..= id obj : "invoice_payload" Data.Aeson.Types.ToJSON..= invoicePayload obj : "shipping_address" Data.Aeson.Types.ToJSON..= shippingAddress obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("from" Data.Aeson.Types.ToJSON..= from obj) GHC.Base.<> (("id" Data.Aeson.Types.ToJSON..= id obj) GHC.Base.<> (("invoice_payload" Data.Aeson.Types.ToJSON..= invoicePayload obj) GHC.Base.<> ("shipping_address" Data.Aeson.Types.ToJSON..= shippingAddress obj))))
instance Data.Aeson.Types.FromJSON.FromJSON ShippingQuery
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "ShippingQuery" (\obj -> (((GHC.Base.pure ShippingQuery GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "from")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "invoice_payload")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "shipping_address"))
-- | Create a new 'ShippingQuery' with all required fields.
mkShippingQuery :: User -- ^ 'from'
  -> Data.Text.Internal.Text -- ^ 'id'
  -> Data.Text.Internal.Text -- ^ 'invoicePayload'
  -> ShippingAddress -- ^ 'shippingAddress'
  -> ShippingQuery
mkShippingQuery from id invoicePayload shippingAddress = ShippingQuery{from = from,
                                                                       id = id,
                                                                       invoicePayload = invoicePayload,
                                                                       shippingAddress = shippingAddress}
